# This workflow will install Python dependencies and run main.py

name: Skola24 to Google Calendar sync

on:
  push:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '30 5,17 * * *'

permissions:
  contents: 'read'
  id-token: 'write'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/54871831620/locations/global/workloadIdentityPools/python-cli-pool/providers/python-cli-provider'
        service_account: 'python-cli@skola24-gcalendar.iam.gserviceaccount.com'

    - name: Run main.py
      run: |
        pipenv run python src/main.py
